# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_history.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_History(object):
    def setupUi(self, History):
        History.setObjectName("History")
        History.resize(794, 586)
        self.verticalLayout = QtWidgets.QVBoxLayout(History)
        self.verticalLayout.setObjectName("verticalLayout")
        self.historyForm = BaseTableWidget(History)
        self.historyForm.setObjectName("historyForm")
        self.historyForm.setColumnCount(5)
        self.historyForm.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.historyForm.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.historyForm.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.historyForm.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.historyForm.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.historyForm.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.historyForm)

        self.retranslateUi(History)
        QtCore.QMetaObject.connectSlotsByName(History)

    def retranslateUi(self, History):
        _translate = QtCore.QCoreApplication.translate
        History.setWindowTitle(_translate("History", "Form"))
        item = self.historyForm.horizontalHeaderItem(0)
        item.setText(_translate("History", "序号"))
        item = self.historyForm.horizontalHeaderItem(1)
        item.setText(_translate("History", "名称"))
        item = self.historyForm.horizontalHeaderItem(2)
        item.setText(_translate("History", "名称"))
        item = self.historyForm.horizontalHeaderItem(3)
        item.setText(_translate("History", "时间"))
        item = self.historyForm.horizontalHeaderItem(4)
        item.setText(_translate("History", "操作"))
from compent.table.base_table_widget import BaseTableWidget
