# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(1028, 535)
        self.verticalLayout = QtWidgets.QVBoxLayout(main_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(main_window)
        self.stackedWidget.setObjectName("stackedWidget")
        self.stackedWidgetPage1 = QtWidgets.QWidget()
        self.stackedWidgetPage1.setObjectName("stackedWidgetPage1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.stackedWidgetPage1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.navigationWidget = NavigationWidget(self.stackedWidgetPage1)
        self.navigationWidget.setMinimumSize(QtCore.QSize(240, 0))
        self.navigationWidget.setMaximumSize(QtCore.QSize(240, 16777215))
        self.navigationWidget.setObjectName("navigationWidget")
        self.horizontalLayout.addWidget(self.navigationWidget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget1 = QtWidgets.QStackedWidget(self.stackedWidgetPage1)
        self.stackedWidget1.setObjectName("stackedWidget1")
        self.stackedWidgetPage1_2 = FormView()
        self.stackedWidgetPage1_2.setObjectName("stackedWidgetPage1_2")
        self.stackedWidget1.addWidget(self.stackedWidgetPage1_2)
        self.verticalLayout_2.addWidget(self.stackedWidget1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.stackedWidget.addWidget(self.stackedWidgetPage1)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Form"))
from compent.widget.navigation_widget import NavigationWidget
from src.view.form.form_view import FormView
