# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_navigation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Navigation(object):
    def setupUi(self, Navigation):
        Navigation.setObjectName("Navigation")
        Navigation.resize(196, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Navigation)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Navigation)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 158, 262))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.edit_btn = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_btn.sizePolicy().hasHeightForWidth())
        self.edit_btn.setSizePolicy(sizePolicy)
        self.edit_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.edit_btn.setObjectName("edit_btn")
        self.verticalLayout_3.addWidget(self.edit_btn)
        self.hsitory_btn = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hsitory_btn.sizePolicy().hasHeightForWidth())
        self.hsitory_btn.setSizePolicy(sizePolicy)
        self.hsitory_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.hsitory_btn.setObjectName("hsitory_btn")
        self.verticalLayout_3.addWidget(self.hsitory_btn)
        self.toolButton_3 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_3.sizePolicy().hasHeightForWidth())
        self.toolButton_3.setSizePolicy(sizePolicy)
        self.toolButton_3.setMinimumSize(QtCore.QSize(0, 40))
        self.toolButton_3.setObjectName("toolButton_3")
        self.verticalLayout_3.addWidget(self.toolButton_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Navigation)
        QtCore.QMetaObject.connectSlotsByName(Navigation)

    def retranslateUi(self, Navigation):
        _translate = QtCore.QCoreApplication.translate
        Navigation.setWindowTitle(_translate("Navigation", "Form"))
        self.edit_btn.setText(_translate("Navigation", "填单"))
        self.hsitory_btn.setText(_translate("Navigation", "历史"))
        self.toolButton_3.setText(_translate("Navigation", "数据维护"))
