# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_navigation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Navigation(object):
    def setupUi(self, Navigation):
        Navigation.setObjectName("Navigation")
        Navigation.resize(434, 334)
        self.verticalLayout = QtWidgets.QVBoxLayout(Navigation)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Navigation)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 388, 156))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.editBtn = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editBtn.sizePolicy().hasHeightForWidth())
        self.editBtn.setSizePolicy(sizePolicy)
        self.editBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.editBtn.setObjectName("editBtn")
        self.verticalLayout_3.addWidget(self.editBtn)
        self.historyBtn = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.historyBtn.sizePolicy().hasHeightForWidth())
        self.historyBtn.setSizePolicy(sizePolicy)
        self.historyBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.historyBtn.setObjectName("historyBtn")
        self.verticalLayout_3.addWidget(self.historyBtn)
        self.dataBtn = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataBtn.sizePolicy().hasHeightForWidth())
        self.dataBtn.setSizePolicy(sizePolicy)
        self.dataBtn.setMinimumSize(QtCore.QSize(0, 40))
        self.dataBtn.setObjectName("dataBtn")
        self.verticalLayout_3.addWidget(self.dataBtn)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Navigation)
        QtCore.QMetaObject.connectSlotsByName(Navigation)

    def retranslateUi(self, Navigation):
        _translate = QtCore.QCoreApplication.translate
        Navigation.setWindowTitle(_translate("Navigation", "Form"))
        self.editBtn.setText(_translate("Navigation", "填单"))
        self.historyBtn.setText(_translate("Navigation", "历史"))
        self.dataBtn.setText(_translate("Navigation", "数据维护"))
